TRANSFORM:
  TRAIN:
    SIZE: [256, 256]
    MEAN: [0.5, 0.5, 0.5]
    STD: [0.5, 0.5, 0.5]
    AUG_PROB: 0.4
    RE_PROB: 0.2

  TEST:
    SIZE: [256, 256]
    MEAN: [0.5, 0.5, 0.5]
    STD: [0.5, 0.5, 0.5]

TRAIN:
  BASE_LR: 2e-5
  WEIGHT_DECAY: 1e-4
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY_BIAS: 0
  FC_LR_FACTOR: 3
  ARCFACE_RADIUS: 30.
  ARCFACE_MARGIN: 0.05

TEST:
  METRIC: cosine_distances
  MAX_RANK: 50
  EVAL_FREQ: 2
  SAVE_FREQ: 2

CAM_NUM: 8